data_processing:

    saving_loading:
        load_data: True # True/False
        save_data: False # True/False
        raw_data_path: "script_data"
        processed_data_path: "processed_data"

    # data processing information
    train_split_ratio: 0.9
    check_raw_data_shape: True
    num_species_total: 6
    specie_train_index: [0,1,2,3,4] # which species should be in the training set
    data_arrange_mode: 'row_major' # each datapoint is a row in the data files
    latent_space_dim: 2

encoder_decoder:
    loading:
        save_model: True # True/False
        load_model: True # True/False
        load_path: 'encoder_decoder_weights.pkl' 

    architecture:
        network_type: 'mlp'
        network_width: 64
        num_layers: 2

    training:

        # Optimizer and learning rate
        optimizer: 'adam'
        start_learning_rate: 0.001 
        end_learning_rate: 0.00001
        learning_rate_decay: 0.9
        learning_rate_decay_steps: 2000

        # batch processing
        num_training_iters: 50000
        batch_size: 128 # number of trajectories to use in a single pass
        
        print_freq: 100

        # experimental settings
        stiffness_reduction: True # yes/no
        simultaneous_training: False # True/False

        # loss function
        stiffness_reduction_weight: 1E-9 # weight for stiffness reduction loss
    
    testing:
        test_model: True # True/False
        plot_results: False # True/False
        save_dir: "enc_dec_results"

neural_ode:
    saving:
        save_model: True # True/False
        load_model: False # True/False
        load_path: 'NODE_weights.pkl' 

    architecture:
        network_type: 'mlp'
        network_width: 64
        num_layers: 2

    training:
       
        # Optimizer and learning rate
        optimizer: 'adam' # 'adam' or 'l-bfgs'
        start_learning_rate: 0.001
        end_learning_rate: 0.00001
        learning_rate_decay: 0.9
        learning_rate_decay_steps: 2000

        # batch processing
        num_training_iters: 5000
        batch_size: 128 # number of trajectories to use in a single pass
        
        print_freq: 100

        simultaneous_training: False # True/False

    ode_solver:
        max_steps: 1000000 # note: currently not used
        pcoeff: 0.3
        icoeff: 0.4
        rtol: 1e-5
        atol: 1e-5
        dtmin: None

    testing:
        test_model: True # True/False
        plot_results: False # True/False
        save_dir: "NODE_results"